import { COLORS } from "./theme";
import { SCREENDIMENSIONS, FONTSIZES,LARGEBTNDIMENSIONS, COMMONDIMENSIONS } from "./dimensions";

export {
    COLORS,
    SCREENDIMENSIONS,
    FONTSIZES,
    LARGEBTNDIMENSIONS,
    COMMONDIMENSIONS
}